experiments:
  - experiment_name: "CV_4W_imu"
    experiment_params:
      kinematics: ["4W"]
      channels: ["imu"]

  - experiment_name: "CV_4W_servo"
    experiment_params:
      kinematics: ["4W"]
      channels: ["servo"]

  - experiment_name: "CV_4W_imu_servo"
    experiment_params:
      kinematics: ["4W"]
      channels: ["imu", "servo"]

  - experiment_name: "CV_6W_imu"
    experiment_params:
      kinematics: ["6W"]
      channels: ["imu"]

  - experiment_name: "CV_6W_servo"
    experiment_params:
      kinematics: ["6W"]
      channels: ["servo"]

  - experiment_name: "CV_6W_imu_servo"
    experiment_params:
      kinematics: ["6W"]
      channels: ["imu", "servo"]

  - experiment_name: "CV_4W_6W_imu"
    experiment_params:
      kinematics: ["4W", "6W"]
      channels: ["imu"]

  - experiment_name: "CV_4W_6W_servo"
    experiment_params:
      kinematics: ["4W", "6W"]
      channels: ["servo"]

  - experiment_name: "CV_4W_6W_imu_servo"
    experiment_params:
      kinematics: ["4W", "6W"]
      channels: ["imu", "servo"]

training_params:
  seed: 0
dataset_params:
  data_dir: "data/train_set/processed"
  labels_file: "data/train_set/labels.json"
  data_frequency: 100.0
  generalized_classes: True
  time_features: ['min', 'max', 'mean', 'std', 'skew', 'kurt', 'rms', 'peak', 'p2p', 'crest', 'form', 'pulse']
  freq_features: ['sum', 'max', 'mean', 'peak', 'var']
